# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-02 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='large_logo',
        ),
        migrations.RemoveField(
            model_name='team',
            name='small_logo',
        ),
        migrations.AddField(
            model_name='team',
            name='logo',
            field=models.FileField(blank=True, help_text=b'SVG Vector Image logo', null=True, upload_to=b'team_logos'),
        ),
    ]
